general {
  lock_cmd = pidof hyprlock || hyprlock

    before_sleep_cmd = loginctl lock-session

    after_sleep_cmd = hyprctl dispatch dpms on
}

# 5 minutos: bloquear
listener {
  timeout = 300
    on-timeout = loginctl lock-session
}

# 5 minutos e 30 segundos: desligar monitor
listener {
  timeout = 330

    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# 30 minutos: suspender
listener {
  timeout = 1800

    on-timeout = systemctl suspend
}
