#!/usr/bin/env bash

chosen=$(printf '%s\n' \
  "󰍃 Sair" \
  "󰤄 Suspender" \
  " Desligar" \
  "󰜉 Reiniciar" |
  rofi -dmenu -i \
  -theme ~/.config/rofi/menu/power.rasi \
  -p ">"
)

case "$chosen" in
  *"Sair")
    hyprctl dispatch 'hl.dsp.exit()'
    ;;
  *"Suspender")
    systemctl suspend
    ;;
  *"Reiniciar")
    systemctl reboot
    ;;
  *"Desligar")
    systemctl poweroff
    ;;
  *)
    exit 1
    ;;
esac
