[bar]
background-opacity = 0

[[bar.layout]]
monitor = "*"
show = true
left = [
    "power",
    "separator",
    "hyprland-workspaces",
    "separator",
    "cava",
]
center = ["clock"]
right = [
    "battery",
    "network",
    "bluetooth",
    "volume",
    "notifications",
]

[modules.clock]
format = "%a %d %H:%M"

[modules.notifications]
label-show = false

[modules.power]
left-click = "systemctl poweroff"
